version: '3.1'

services:

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

      - ./gbaranov/gbaranov-site:/usr/share/nginx/gbaranov/gbaranov-site/html

      - ./totrno/totrno-site:/usr/share/nginx/totrno/totrno-site/html
    
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
